swagger: "2.0"
info:
  description: "Book an appointment with a dentist"
  version: "1.0.0"
  title: "Chatbot"
basePath: "/v33"
schemes: 
  - https
paths:
  /ask:

    post:
      summary: get questions of students
      parameters:
        - in: body
          name: questions
          description: student question
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
              
      tags:
        - Appointment
      
      responses:
        200:
          description: successful